#!/bin/sh
# postinst for vadsll, UbuntuLTS build

# msg show to user
_msg() {
  echo "  Please modify config file with command \`vadsll-conf\` "
  echo "  And set password with command \`vadsll-passwd\` "
  echo "  More information online <https://github.com/sceext222/vadsll> "
}

post_install() {
  # create vadsll system user
  # NOTE shell is /usr/sbin/nologin
  useradd --system --shell /usr/sbin/nologin --home-dir /usr/lib/vadsll --comment "System user for VADSLL " vadsll

  _msg
}

post_install
